# Generated by Django 2.0.1 on 2018-01-08 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20180108_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='last_edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_edit_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='last_edit_user_set+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='last_edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_edit_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='last_edit_user_set+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dance',
            name='last_edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dance',
            name='last_edit_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='last_edit_user_set+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='last_edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='label',
            name='last_edit_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='last_edit_user_set+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='last_edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='last_edit_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='last_edit_user_set+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_user_set+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_user_set+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dance',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_user_set+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='label',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_user_set+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_user_set+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creation_user_set+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='last_edit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_edit_user_set+', to=settings.AUTH_USER_MODEL),
        ),
    ]
